languages:
  PHP: true
ratings:
  paths:
  - src/**
exclude_paths:
 - vendor/**
 - tests/**
engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
