languages:
  PHP: true
ratings:
  paths:
  - appservice/src/**
exclude_paths:
 - appservice/vendor/**
 - appservice/tests/**
engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
